/**
 * MDLH SQL Queries for Metadata Lakehouse Gold Layer
 */

// Hierarchy queries
export const SQL_HIERARCHY_CONNECTORS = `
SELECT
  CONNECTOR_NAME,
  COUNT(*) AS ASSET_COUNT
FROM ATLAN_GOLD.PUBLIC.ASSETS
WHERE STATUS = 'ACTIVE' AND CONNECTOR_NAME IS NOT NULL
GROUP BY CONNECTOR_NAME
ORDER BY ASSET_COUNT DESC
`;

export const SQL_HIERARCHY_DATABASES = `
SELECT DISTINCT
  SPLIT_PART(ASSET_QUALIFIED_NAME, '/', 4) AS DATABASE_NAME,
  MIN(GUID) AS SAMPLE_GUID,
  COUNT(*) AS ASSET_COUNT
FROM ATLAN_GOLD.PUBLIC.ASSETS
WHERE STATUS = 'ACTIVE'
  AND CONNECTOR_NAME = ?
  AND ASSET_QUALIFIED_NAME IS NOT NULL
  AND UPPER(ASSET_TYPE) IN ('DATABASE', 'TABLE', 'VIEW', 'MATERIALIZEDVIEW', 'SCHEMA')
GROUP BY DATABASE_NAME
HAVING DATABASE_NAME IS NOT NULL AND DATABASE_NAME != ''
ORDER BY ASSET_COUNT DESC
`;

export const SQL_HIERARCHY_SCHEMAS = `
SELECT DISTINCT
  SPLIT_PART(ASSET_QUALIFIED_NAME, '/', 5) AS SCHEMA_NAME,
  MIN(GUID) AS SAMPLE_GUID,
  COUNT(*) AS ASSET_COUNT
FROM ATLAN_GOLD.PUBLIC.ASSETS
WHERE STATUS = 'ACTIVE'
  AND CONNECTOR_NAME = ?
  AND SPLIT_PART(ASSET_QUALIFIED_NAME, '/', 4) = ?
  AND ASSET_QUALIFIED_NAME IS NOT NULL
  AND UPPER(ASSET_TYPE) IN ('SCHEMA', 'TABLE', 'VIEW', 'MATERIALIZEDVIEW')
GROUP BY SCHEMA_NAME
HAVING SCHEMA_NAME IS NOT NULL AND SCHEMA_NAME != ''
ORDER BY ASSET_COUNT DESC
`;

export const SQL_HIERARCHY_TABLES = `
SELECT
  GUID,
  ASSET_NAME,
  ASSET_TYPE,
  ASSET_QUALIFIED_NAME,
  DESCRIPTION,
  CERTIFICATE_STATUS,
  HAS_LINEAGE,
  POPULARITY_SCORE,
  OWNER_USERS,
  TAGS,
  UPDATED_AT
FROM ATLAN_GOLD.PUBLIC.ASSETS
WHERE STATUS = 'ACTIVE'
  AND CONNECTOR_NAME = ?
  AND SPLIT_PART(ASSET_QUALIFIED_NAME, '/', 4) = ?
  AND SPLIT_PART(ASSET_QUALIFIED_NAME, '/', 5) = ?
  AND UPPER(ASSET_TYPE) IN ('TABLE', 'VIEW', 'MATERIALIZEDVIEW')
ORDER BY POPULARITY_SCORE DESC NULLS LAST, ASSET_NAME ASC
LIMIT ?
`;

// Quality scoring query
export const SQL_QUALITY_SCORES = `
SELECT
  A.GUID,
  A.ASSET_NAME,
  A.ASSET_TYPE,
  A.ASSET_QUALIFIED_NAME,
  A.CONNECTOR_NAME,
  A.DESCRIPTION,
  A.OWNER_USERS,
  A.TAGS,
  A.TERM_GUIDS,
  A.CERTIFICATE_STATUS,
  A.HAS_LINEAGE,
  A.README_GUID,
  A.POPULARITY_SCORE,
  A.UPDATED_AT,
  A.SOURCE_UPDATED_AT,
  R.TABLE_COLUMN_COUNT,
  R.TABLE_ROW_COUNT,
  R.TABLE_SIZE_BYTES,
  R.TABLE_TOTAL_READ_COUNT,
  -- Completeness Score (8 signals)
  (CASE WHEN A.DESCRIPTION IS NOT NULL AND TRIM(A.DESCRIPTION) != '' THEN 1 ELSE 0 END +
   CASE WHEN A.OWNER_USERS IS NOT NULL AND ARRAY_SIZE(A.OWNER_USERS) > 0 THEN 1 ELSE 0 END +
   CASE WHEN A.CERTIFICATE_STATUS IS NOT NULL AND A.CERTIFICATE_STATUS != '' THEN 1 ELSE 0 END +
   CASE WHEN A.TAGS IS NOT NULL AND ARRAY_SIZE(A.TAGS) > 0 THEN 1 ELSE 0 END +
   CASE WHEN A.TERM_GUIDS IS NOT NULL AND ARRAY_SIZE(A.TERM_GUIDS) > 0 THEN 1 ELSE 0 END +
   CASE WHEN A.README_GUID IS NOT NULL THEN 1 ELSE 0 END +
   CASE WHEN A.HAS_LINEAGE = TRUE THEN 1 ELSE 0 END +
   CASE WHEN R.TABLE_COLUMN_COUNT > 0 OR A.ASSET_TYPE NOT IN ('Table','View') THEN 1 ELSE 0 END
  ) / 8.0 * 100 AS COMPLETENESS_SCORE,
  -- Accuracy Score (5 signals)
  (CASE WHEN REGEXP_LIKE(A.ASSET_NAME, '^[\\\\w\\\\-\\\\.]+$') THEN 1 ELSE 0 END +
   CASE WHEN A.OWNER_USERS IS NOT NULL AND ARRAY_SIZE(A.OWNER_USERS) > 0 THEN 1 ELSE 0 END +
   CASE WHEN A.CERTIFICATE_STATUS IS NOT NULL AND A.CERTIFICATE_STATUS != '' THEN 1 ELSE 0 END +
   CASE WHEN A.TAGS IS NOT NULL AND ARRAY_SIZE(A.TAGS) > 0 THEN 1 ELSE 0 END +
   1
  ) / 5.0 * 100 AS ACCURACY_SCORE,
  -- Timeliness Score
  CASE WHEN DATEDIFF('day', TO_TIMESTAMP(COALESCE(A.SOURCE_UPDATED_AT, A.UPDATED_AT, 0)/1000), CURRENT_TIMESTAMP()) <= 90
       THEN 100.0 ELSE 0.0 END AS TIMELINESS_SCORE,
  -- Consistency Score (4 signals)
  (CASE WHEN A.TERM_GUIDS IS NOT NULL AND ARRAY_SIZE(A.TERM_GUIDS) > 0 THEN 1 ELSE 0 END +
   CASE WHEN A.TAGS IS NOT NULL AND ARRAY_SIZE(A.TAGS) > 0 THEN 1 ELSE 0 END +
   CASE WHEN ARRAY_SIZE(SPLIT(A.ASSET_QUALIFIED_NAME, '/')) >= 2 THEN 1 ELSE 0 END +
   CASE WHEN A.CONNECTOR_QUALIFIED_NAME IS NOT NULL THEN 1 ELSE 0 END
  ) / 4.0 * 100 AS CONSISTENCY_SCORE,
  -- Usability Score (3 signals)
  (CASE WHEN COALESCE(A.POPULARITY_SCORE, 0) > 0 THEN 1 ELSE 0 END +
   CASE WHEN COALESCE(R.TABLE_TOTAL_READ_COUNT, 0) > 0 THEN 1 ELSE 0 END +
   1
  ) / 3.0 * 100 AS USABILITY_SCORE
FROM ATLAN_GOLD.PUBLIC.ASSETS A
LEFT JOIN ATLAN_GOLD.PUBLIC.RELATIONAL_ASSET_DETAILS R ON A.GUID = R.GUID
WHERE A.STATUS = 'ACTIVE'
`;

// Asset detail query
export const SQL_ASSET_DETAIL = `
SELECT
  A.*,
  R.TABLE_COLUMN_COUNT,
  R.TABLE_ROW_COUNT,
  R.TABLE_SIZE_BYTES,
  R.TABLE_TOTAL_READ_COUNT,
  SPLIT_PART(A.ASSET_QUALIFIED_NAME, '/', 4) AS DATABASE_NAME,
  SPLIT_PART(A.ASSET_QUALIFIED_NAME, '/', 5) AS SCHEMA_NAME
FROM ATLAN_GOLD.PUBLIC.ASSETS A
LEFT JOIN ATLAN_GOLD.PUBLIC.RELATIONAL_ASSET_DETAILS R ON A.GUID = R.GUID
WHERE A.GUID = ?
`;

// Lineage query
export const SQL_LINEAGE = `
SELECT
  DIRECTION,
  START_GUID,
  RELATED_GUID,
  RELATED_NAME,
  RELATED_TYPE,
  LEVEL
FROM ATLAN_GOLD.PUBLIC.LINEAGE
WHERE START_GUID = ?
ORDER BY LEVEL
`;

// Schema introspection
export const SQL_GET_SCHEMA_COLUMNS = `
SELECT
  TABLE_NAME,
  COLUMN_NAME,
  DATA_TYPE,
  IS_NULLABLE,
  COMMENT
FROM ATLAN_GOLD.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'PUBLIC'
ORDER BY TABLE_NAME, ORDINAL_POSITION
`;

// Quality rollup by dimension
export function buildQualityRollupQuery(dimension, assetTypeFilter = '') {
  const dimensionMap = {
    connector: 'A.CONNECTOR_NAME',
    database: "SPLIT_PART(A.ASSET_QUALIFIED_NAME, '/', 4)",
    schema: "SPLIT_PART(A.ASSET_QUALIFIED_NAME, '/', 5)",
    asset_type: 'A.ASSET_TYPE',
    certificate_status: "COALESCE(A.CERTIFICATE_STATUS, 'NONE')",
  };

  const dimensionSql = dimensionMap[dimension] || 'A.CONNECTOR_NAME';
  const typeFilter = assetTypeFilter
    ? `AND UPPER(A.ASSET_TYPE) IN (${assetTypeFilter.split(',').map(t => `'${t.trim().toUpperCase()}'`).join(',')})`
    : '';

  return `
SELECT
  ${dimensionSql} AS DIMENSION_VALUE,
  COUNT(*) AS TOTAL_ASSETS,
  AVG(CASE WHEN A.DESCRIPTION IS NOT NULL AND TRIM(A.DESCRIPTION) != '' THEN 1.0 ELSE 0.0 END) * 100 AS PCT_WITH_DESCRIPTION,
  AVG(CASE WHEN A.OWNER_USERS IS NOT NULL AND ARRAY_SIZE(A.OWNER_USERS) > 0 THEN 1.0 ELSE 0.0 END) * 100 AS PCT_WITH_OWNER,
  AVG(CASE WHEN A.TAGS IS NOT NULL AND ARRAY_SIZE(A.TAGS) > 0 THEN 1.0 ELSE 0.0 END) * 100 AS PCT_WITH_TAGS,
  AVG(CASE WHEN UPPER(COALESCE(A.CERTIFICATE_STATUS, '')) = 'VERIFIED' THEN 1.0 ELSE 0.0 END) * 100 AS PCT_CERTIFIED,
  AVG(CASE WHEN A.HAS_LINEAGE = TRUE THEN 1.0 ELSE 0.0 END) * 100 AS PCT_WITH_LINEAGE,
  AVG(CASE WHEN A.README_GUID IS NOT NULL THEN 1.0 ELSE 0.0 END) * 100 AS PCT_WITH_README,
  AVG(CASE WHEN A.TERM_GUIDS IS NOT NULL AND ARRAY_SIZE(A.TERM_GUIDS) > 0 THEN 1.0 ELSE 0.0 END) * 100 AS PCT_WITH_TERMS
FROM ATLAN_GOLD.PUBLIC.ASSETS A
LEFT JOIN ATLAN_GOLD.PUBLIC.RELATIONAL_ASSET_DETAILS R ON A.GUID = R.GUID
WHERE A.STATUS = 'ACTIVE'
${typeFilter}
GROUP BY ${dimensionSql}
ORDER BY TOTAL_ASSETS DESC
`;
}
